name: local_video_player
description: "A new Flutter project."

publish_to: "none"

version: 2.0.3+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.9.0
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  get_thumbnail_video: ^0.7.3
  path_provider: ^2.1.5
  video_player: ^2.9.2
  popover: ^0.3.1
  share_plus: ^10.1.4
  receive_intent: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
